In [89]:
import pandas as pd
data = pd.read_csv("dataset.csv", header=None)
data

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  \
0    07:00   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
1    07:30   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
2    08:00   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
3    08:30   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
4    09:00   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
..     ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..   
130  18:00   1   0   0   0   1   0   0   0   0   0   0   0   1   0   0   0   
131  18:30   0   0   0   2   0   0   0   0   0   0   0   0   0   0   0   0   
132  19:00   1   0   0   2   0   0   0   0   0   0   0   0   0   0   0   0   
133  19:30   0   4   0   0   0   0   0   0   0   0   0   1   0   0   1   0   
134  20:00   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

       17  
0     4.1  
1     6.6  
2     8.7  
3     9.2  
4    11.1  
..    ...  
130  17.8  
131  18.1  
132  17.7  
133  17.4  
134  12.1  

[135 rows x 18 columns]

In [90]:
day = ['06:00', '06:30', '07:00', '07:30', '08:00', '08:30', '09:00', '09:30', '10:00' ,'10:30', '11:00', '11:30', '12:00',
      '12:30', '13:00', '13:30', '14:00', '14:30', '15:00', '15:30', '16:00', '16:30', '17:00', '17:30' ]
night = ['18:00', '18:30', '19:00', '19:30', '20:00', '20:30', '21:00', '21:30', '22:00', '22:30', '23:00', '23:30', '00:00', 
        '00:30', '01:00', '01:30', '02:00', '02:30', '03:00', '03:30', '04:00', '04:30', '05:00', '05:30']
j=0
for i in data[0]:
    if(i in day):
        data[0][j] = 'day'
    if(i in night):
        data[0][j] = 'night'
    j+=1

<ipython-input-90-9ad3e39e6b19>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[0][j] = 'day'
<ipython-input-90-9ad3e39e6b19>:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[0][j] = 'night'


In [91]:
data = data.rename(columns={0 : 'hour'})
data

hour  1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16    17
0      day  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   4.1
1      day  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   6.6
2      day  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   8.7
3      day  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   9.2
4      day  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0  11.1
..     ... .. .. .. .. .. .. .. .. ..  ..  ..  ..  ..  ..  ..  ..   ...
130  night  1  0  0  0  1  0  0  0  0   0   0   0   1   0   0   0  17.8
131  night  0  0  0  2  0  0  0  0  0   0   0   0   0   0   0   0  18.1
132  night  1  0  0  2  0  0  0  0  0   0   0   0   0   0   0   0  17.7
133  night  0  4  0  0  0  0  0  0  0   0   0   1   0   0   1   0  17.4
134  night  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0  12.1

[135 rows x 18 columns]

In [92]:
data = pd.get_dummies(data, columns=['hour'])
data

1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16    17  hour_day  \
0    0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   4.1         1   
1    0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   6.6         1   
2    0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   8.7         1   
3    0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   9.2         1   
4    0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0  11.1         1   
..  .. .. .. .. .. .. .. .. ..  ..  ..  ..  ..  ..  ..  ..   ...       ...   
130  1  0  0  0  1  0  0  0  0   0   0   0   1   0   0   0  17.8         0   
131  0  0  0  2  0  0  0  0  0   0   0   0   0   0   0   0  18.1         0   
132  1  0  0  2  0  0  0  0  0   0   0   0   0   0   0   0  17.7         0   
133  0  4  0  0  0  0  0  0  0   0   0   1   0   0   1   0  17.4         0   
134  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0  12.1         0   

     hour_night  
0             0  
1             0  
2             0  
3             0  
4             0  
..          ...  
130           1  
131           1  
132           1  
133           1  
134           1  

[135 rows x 19 columns]

In [93]:
data1 = data.drop(17, axis=1, inplace=False)
data1

1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  hour_day  \
0    0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0         1   
1    0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0         1   
2    0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0         1   
3    0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0         1   
4    0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0         1   
..  .. .. .. .. .. .. .. .. ..  ..  ..  ..  ..  ..  ..  ..       ...   
130  1  0  0  0  1  0  0  0  0   0   0   0   1   0   0   0         0   
131  0  0  0  2  0  0  0  0  0   0   0   0   0   0   0   0         0   
132  1  0  0  2  0  0  0  0  0   0   0   0   0   0   0   0         0   
133  0  4  0  0  0  0  0  0  0   0   0   1   0   0   1   0         0   
134  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0         0   

     hour_night  
0             0  
1             0  
2             0  
3             0  
4             0  
..          ...  
130           1  
131           1  
132           1  
133           1  
134           1  

[135 rows x 18 columns]

In [94]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(data1)
X = scaler.transform(data1)
X

array([[0.  , 0.  , 0.  , ..., 0.  , 1.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.  , 1.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.  , 1.  , 0.  ],
       ...,
       [0.25, 0.  , 0.  , ..., 0.  , 0.  , 1.  ],
       [0.  , 0.8 , 0.  , ..., 0.  , 0.  , 1.  ],
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 1.  ]])

In [96]:
print("Reducing training size")
X = data1[['hour_day', 'hour_night']].to_numpy()
X

Reducing training size


array([[1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1,

In [97]:
Y = data[17].to_numpy()
Y

array([ 4.1,  6.6,  8.7,  9.2, 11.1, 10.9,  8.3,  8.2,  7.6,  6.4,  5.2,
        4.7,  4.8,  4.9,  5.1,  5.3,  6.9,  5.1,  6.7,  8.1,  9.5,  9.4,
        9.9, 11.2, 11.8, 11.4,  7.4,  4.9,  6.3,  8. ,  9.5, 10.3,  9.5,
        7.9,  7.7,  8.3,  8.5,  8.5,  7.4,  8.7,  7.8,  8.1,  8.3,  8.3,
        8.4,  9.3, 11. , 12.1, 13.1, 13.7, 15.3, 16.8, 15.6, 11. ,  3.4,
        3.8,  5.3,  5.9,  7. ,  7.4,  6.2,  6.5,  6.7,  7.7,  8.7,  8.2,
        8. ,  6.2,  6.8,  8. ,  9.2, 10.1, 12.2, 13.9, 15. , 17.1, 19.6,
       20.2, 22.6, 23.4, 19.3,  4. ,  5. ,  5.7,  5.6,  8.5,  7.6,  7.6,
        6.6,  7.4,  7.7,  7.7,  7.9, 10.1, 10.8, 11.4, 12.5, 12.1, 10.5,
        9.9, 11.1, 12.1, 13.7, 15.6, 18.3, 19.9, 21.5, 22.1,  3.4,  5. ,
        5.5,  6.4,  8.2,  9. , 10.1, 10.3, 10.9, 12.3, 11.9, 10.3, 11. ,
        9.7, 10.3, 10.9,  8.9,  9.4, 11.3, 13. , 14.6, 17.4, 17.8, 18.1,
       17.7, 17.4, 12.1])

In [100]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, shuffle=False)
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
print("Linear Regression with train:test as 80:20")
print(f"\nMSE: {mse}")
print("R2 score: ", model.score(X_test, y_test))

Linear Regression with train:test as 80:20

MSE: 11.024600378787882
R2 score:  0.27558122749872316


In [101]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, shuffle=False)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print("Linear Regression with train:test as 70:30")
print(f"\nMSE: {mse}")
print("R2 score: ", model.score(X_test, y_test))

Linear Regression with train:test as 70:30

MSE: 14.29113253426397
R2 score:  0.21180453577850256


In [102]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.1, shuffle=False)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print("Linear Regression with train:test as 90:10")
print(f"\nMSE: {mse}")
print("R2 score: ", model.score(X_test, y_test))

Linear Regression with train:test as 90:10

MSE: 13.711761021328442
R2 score:  -0.16082912635859947


In [103]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import median_absolute_error
from sklearn.metrics import r2_score
poly = PolynomialFeatures(degree = 2)
X_poly = poly.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X_poly, Y, test_size=0.2, shuffle=False)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print("Polynomial regression")
print(f"\nMSE: {mse}")
rmse = mean_squared_error(y_test, y_pred, squared=False)
print(f"\nRMSE: {rmse}")
mea = mean_absolute_error(y_test, y_pred)
print(f"\nMEA: {mea}")
mdea = median_absolute_error(y_test, y_pred)
print(f"\nMDEA: {mdea}")
r2 = r2_score(y_test, y_pred)
print(f"\nR2 Square: {r2}")

Polynomial regression

MSE: 10.869522569444442

RMSE: 3.2968958990912105

MEA: 2.7250000000000005

MDEA: 2.1000000000000014

R2 Square: 0.28577128177977573


In [104]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import median_absolute_error
from sklearn.metrics import r2_score
poly = PolynomialFeatures(degree = 2)
X_poly = poly.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X_poly, Y, test_size=0.2, shuffle=True)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print("Shuffling of training data")
print(f"\nMSE: {mse}")
rmse = mean_squared_error(y_test, y_pred, squared=False)
print(f"\nRMSE: {rmse}")
mea = mean_absolute_error(y_test, y_pred)
print(f"\nMEA: {mea}")
mdea = median_absolute_error(y_test, y_pred)
print(f"\nMDEA: {mdea}")
r2 = r2_score(y_test, y_pred)
print(f"\nR2 Square: {r2}")

Shuffling of training data

MSE: 9.952690972222225

RMSE: 3.154788578054356

MEA: 2.450462962962963

MDEA: 1.7562499999999996

R2 Square: 0.4305204057304993


In [105]:
i=3
for i in [3,4]:
    from sklearn.preprocessing import PolynomialFeatures
    from sklearn.metrics import mean_absolute_error
    from sklearn.metrics import median_absolute_error
    from sklearn.metrics import r2_score
    poly = PolynomialFeatures(degree = i)
    X_poly = poly.fit_transform(X)
    X_train, X_test, y_train, y_test = train_test_split(X_poly, Y, test_size=0.2, shuffle=True)
    model = LinearRegression()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    print("Polynomial regression with degree : ", i)
    print(f"\nMSE: {mse}")
    rmse = mean_squared_error(y_test, y_pred, squared=False)
    print(f"\nRMSE: {rmse}")
    mea = mean_absolute_error(y_test, y_pred)
    print(f"\nMEA: {mea}")
    mdea = median_absolute_error(y_test, y_pred)
    print(f"\nMDEA: {mdea}")
    r2 = r2_score(y_test, y_pred)
    print(f"\nR2 Square: {r2}\n")

Polynomial regression with degree :  3

MSE: 9.867916666666668

RMSE: 3.1413240308294634

MEA: 2.636574074074074

MDEA: 2.3375000000000004

R2 Square: 0.42105630079239753

Polynomial regression with degree :  4

MSE: 11.542718460648146

RMSE: 3.3974576466305133

MEA: 2.737731481481482

MDEA: 2.2375

R2 Square: 0.025584644249430744

